{
 "title": "Sonarqube - Project",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "15m",
 "templating": {
  "list": [
   { "name": "project", "label": "Projects", "query": "label_values(sonar_bugs, key)" }
  ]
 },
 "panels": [
  { "title": "Security", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Security Rating",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "repeat": "project",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Security Remediation Effort",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonar_security_remediation_effort{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Security Hostspots",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonar_security_hotspots{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Reliability", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Reliability Rating",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 14 },
   "repeat": "project",
   "targets": [
    {
     "expr": "sonar_reliability_rating{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Remediation Reliability Effort (Bugs)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sonar_reliability_remediation_effort{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Bugs",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonar_bugs{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Code Smells", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Code Smells",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 27 },
   "repeat": "project",
   "targets": [
    {
     "expr": "sonar_sqale_rating{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Maintainability Debt",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "m" }
   ],
   "targets": [
    {
     "expr": "sonar_sqale_index{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Code Smells",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonar_code_smells{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  { "title": "Coverage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 } },
  {
   "title": "Line Coverage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 42 },
   "repeat": "project",
   "targets": [
    {
     "expr": "sonar_line_coverage{key=~\"^$project$\"}",
     "legendFormat": "{{key}}"
    }
   ]
  },
  {
   "title": "Lines to Cover",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sonar_lines_to_cover{key=~\"^$project\"}",
     "legendFormat": "{{key}}"
    }
   ]
  }
 ]
}